//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTrafficManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public Airline()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Flights = new HashSet<Flight>();
        }
    
        public int idAirline { get; set; }
        public string companyName { get; set; }
        public byte[] logo { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
