//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTrafficManagement.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirplaneTrafficEntities : DbContext
    {
        public AirplaneTrafficEntities()
            : base("name=AirplaneTrafficEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }


        public AirplaneTrafficEntities(bool isProxyCreationEnabled)
            : this()
        {
            // Disable lazy loading.
            Configuration.LazyLoadingEnabled = false;
            // Disable/Enable proxy object creation.
            Configuration.ProxyCreationEnabled = isProxyCreationEnabled;

            var context = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }
    }  
}
