

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirplaneTrafficManagement.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AirplaneTrafficEntities : DbContext
{
    public AirplaneTrafficEntities()
        : base("name=AirplaneTrafficEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Airline> Airline { get; set; }

    public virtual DbSet<Airport> Airport { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Flight> Flight { get; set; }

    public virtual DbSet<Passenger> Passenger { get; set; }

    public virtual DbSet<Route> Route { get; set; }

    public virtual DbSet<Ticket> Ticket { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

