
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirplaneTrafficManagement.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public int idClient { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string email { get; set; }

    public Nullable<int> phone { get; set; }

    public string city { get; set; }

    public Nullable<int> idPassenger { get; set; }

    public Nullable<int> idTicket { get; set; }

    public string address { get; set; }

    public string confirmPassword { get; set; }

    public string userType { get; set; }



    public virtual Passenger Passenger { get; set; }

    public virtual Ticket Ticket { get; set; }

}

}
