
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirplaneTrafficManagement.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Flight
{

    public Flight()
    {

        this.Ticket = new HashSet<Ticket>();

    }


    public int idFlight { get; set; }

    public Nullable<System.DateTime> departOn { get; set; }

    public Nullable<System.DateTime> returnOn { get; set; }

    public Nullable<int> idAirport { get; set; }

    public Nullable<int> idRoute { get; set; }

    public Nullable<int> idAirline { get; set; }

    public Nullable<int> departureFrom { get; set; }

    public Nullable<int> arriveAt { get; set; }

    public Nullable<double> price { get; set; }



    public virtual Airport Departure { get; set; }

    public virtual Airport Arrival { get; set; }

    public virtual ICollection<Ticket> Ticket { get; set; }

}

}
