
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirplaneTrafficManagement.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Route
{

    public int idRoute { get; set; }

    public string leavingFrom { get; set; }

    public string goingTo { get; set; }

    public Nullable<System.TimeSpan> leavingHour { get; set; }

    public Nullable<System.TimeSpan> arrivalHour { get; set; }

    public Nullable<int> idAirport { get; set; }



    public virtual Airport Airport { get; set; }

}

}
