//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTrafficManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int idTicket { get; set; }
        public Nullable<int> idAirline { get; set; }
        public Nullable<int> seat { get; set; }
        public Nullable<int> availableTickets { get; set; }
        public Nullable<int> totalTickets { get; set; }
        public Nullable<int> idFlight { get; set; }
        public string @class { get; set; }
        public Nullable<bool> roundTrip { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
