//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTrafficManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int idUserType { get; set; }
        public Nullable<bool> admin { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
